Add CC0 license
ChainAgnostic/CAIPs pull request #177
Opened 2022-11-17 16:50 UTC by ligi

as it came up in the meeting today
inline to not rely on the external link

2022-11-17 16:51 UTC, ukstv approved these changes

2022-11-17 17:21 UTC, ritave requested changes
I'd say to get this in we need to update the template, sip-1 process, and all CC0 links in all SIPs?

2022-11-18 09:52 UTC, ligi commented
SIP?

2022-11-18 11:18 UTC, ritave commented
My bad, I said Snaps Improvement Proposals, when I meant CAIPs

2022-11-18 13:16 UTC, merged