Blockchain Reference for Filecoin Namespace
ChainAgnostic/CAIPs pull request #23
Opened 2020-08-27 10:51 UTC by ukstv

This pull request adds CAIP-2 chain id for Filecoin.

2020-08-28 11:41 UTC, oed approved these changes

2020-08-30 16:01 UTC, ligi commented on CAIPs/caip-draft_filecoin_namespace.md
> +caip: <to be assigned>
please set to 23 - also the filename

2020-08-30 16:04 UTC, ligi requested changes
DIP number is 23 - please set header and filename accordingly

2020-08-30 16:09 UTC, ligi commented
Thanks for the PR! Does Filecoin have a concept similar to chainID's like in EIP155? Just having `t` and `f` feels lacking upgrade paths a bit. Would love some other opinions before merging.

2020-08-31 04:13 UTC, vasa-develop commented
cc @arajasek

2020-08-31 06:28 UTC, oed commented
Some context from the filecoin slack:

---

**Aayush Rajasekaran Aug 28th at 4:09 AM**
Hey @Joel! I may be missing some context, but this looks broadly good to me (testnet addresses will start t, and mainnet ones will start with f).

**Joel  3 days ago**
Thanks @Aayush Rajasekaran Context: CAIP-2 is a standard to represent any blockchain system by having a namespace and a chainId. There are currently CAIP-2 specs for a number of popular blockchains.So if I understand correctly filecoin adds a chain identifier to each address on the blockchain which tell users which chain the address is associated with. Currently you have f and t, so that seems appropriate here as you said. Is there any plan for how to deal with potential forks or new networks based on filecoin in the future?

**Aayush Rajasekaran  3 days ago**
No plan that I’m aware of, but maybe good to think about now…I’ll poke the team. For now, though, yeah f for mainnet addresses sounds good to me.Do you typically include testnet stuff in the spec? I don’t think there’s anything wrong with that, just wondering whether we want to specify the t addresses at all.An additional note is that you could include more info in this spec if you chose. Filecoin has (loosely speaking) 4 kinds of addresses:

    ID addresses, which start f0
    Secp addresses, which start f1
    Multisig addresses, which start f2
    BLS addresses, which start f3

I’m not sure whether you wanna include that detail (it’s a little more vulnerable to change than just the f prefix).

2020-09-01 08:17 UTC, oed requested changes
Can you also add CAIP-23 to the list in README.md?

2020-09-02 14:08 UTC, ukstv commented
@oed There. Links to master branch. The link would be all right after merge.

2020-09-02 14:46 UTC, ligi approved these changes

2020-09-04 09:33 UTC, oed approved these changes

2020-09-14 08:31 UTC, oed commented
Ping @ligi, anything blocking a merge here?
Also, welcome back to Berlin :)

2020-09-20 14:46 UTC, merged

2020-09-20 14:46 UTC, ligi commented
Sorry for the late merge - what a wild year ..