Implementation of CAIP-2 for EOSIO blockchains
ChainAgnostic/CAIPs pull request #33
Opened 2020-11-30 15:45 UTC by sebastianmontero

Initial draft of the CAIP-2 for EOSIO blockchains.

2020-12-02 10:01 UTC, ligi requested changes
Please also add your CAIP to the list in the README

2020-12-03 03:54 UTC, ligi approved these changes
LGTM

2020-12-03 03:55 UTC, ligi commented
LGTM - but would love some more eye-ballz on it before the merge  @pedrouid @webmaster128 @rekmarks

2020-12-03 07:53 UTC, webmaster128 commented on CAIPs/caip-7.md
> +The namespace "EOSIO" refers to the EOSIO open-source blockchain platform.
```suggestion
The namespace "eosio" refers to the EOSIO open-source blockchain platform.
```

2020-12-03 07:53 UTC, webmaster128 commented on CAIPs/caip-7.md
> +The Chain ID is the SHA256 hash of the genesis state of the chain, and its represented as hexadecimal number of 64 digits
```suggestion
The Chain ID is the SHA256 hash of the genesis state of the chain, represented as lower case hexadecimal number of 64 digits.
```

2020-12-03 07:58 UTC, webmaster128 requested changes
Oh, and this conflicts with https://github.com/ChainAgnostic/CAIPs/blob/master/CAIPs/caip-2.md#syntax. The reference part must not exceed 47 characters, which is why we use prefixes in https://github.com/ChainAgnostic/CAIPs/blob/master/CAIPs/caip-4.md

2020-12-03 09:17 UTC, webmaster128 commented
The alternative to prefixes is to use [a different encoding](https://en.wikipedia.org/wiki/Binary-to-text_encoding#Encoding_standards) for the 32 bytes. CAIP-2 is case-sensitive and you need 32/47 = 68 % efficiency. So candidates are [Base58](https://de.wikipedia.org/wiki/Base58) or [Base62](https://en.wikipedia.org/wiki/Base62) (no idea how this encoding works but promising in theory).

However, I think it is easier for human consumption to use a prefix of the default encoding than to re-encode it.

2020-12-04 15:04 UTC, sebastianmontero commented
I've updated the reference definition, to use a 32 character prefix of the Chain ID

2020-12-04 15:11 UTC, webmaster128 reviewed
Some wording 💅 but otherwise 👍

2020-12-04 15:11 UTC, webmaster128 commented on CAIPs/caip-7.md
> +The Chain ID, as defined by EOSIO, is the SHA256 hash of the genesis state of the chain, represented as lower case hexadecimal number of 64 digits. In order to fit the reference restrictions, the for
```suggestion
The Chain ID, as defined by EOSIO, is the SHA256 hash of the genesis state of the chain, represented as lower case hexadecimal number of 64 digits. In order to fit the CAIP-2 reference format, a 32 character prefix of the Chain ID is used.
```

2020-12-04 15:18 UTC, webmaster128 approved these changes
Cool and welcome

2020-12-04 15:25 UTC, sebastianmontero commented
Great! Thanks!

2020-12-07 14:49 UTC, webmaster128 commented
@ligi can we merge this? I don't have permissions to do so.

2020-12-07 14:55 UTC, merged