feat: CAIP-XX for ERC1155 assets
ChainAgnostic/CAIPs pull request #46
Opened 2021-03-22 19:04 UTC by shrugs

An asset reference and token id specification for blockchain references to ERC1155 tokens on an eip155 chain. Based on the CAIP-22 specification.

2021-03-23 09:45 UTC, ligi requested changes
Looks really good to me - thanks for the PR
Only change to CAIP-29 (filename and header)
and add to the README
Thanks for the PR!

2021-03-23 09:45 UTC, ligi commented on CAIPs/CAIP-XX.md
> +caip: <to be assigned>
```suggestion
caip: 29
```

2021-03-23 13:26 UTC, shrugs commented
done! thanks for the quick review.

2021-03-24 06:45 UTC, ligi commented
You are most welcome! Would still give some other reviewers some time to look over it before merging though. Hope @antoineherzog @pedrouid and @oed can approve or give comments here as they have most domain knowledge in this area.
Hope you still have a bit of time to wait for them. Otherwise I also feel quite confident already merging - don't think they will have significant objections in this particular case.

2021-03-24 07:55 UTC, oed approved these changes
lgtm

2021-03-24 08:35 UTC, antoineherzog approved these changes
LGTM!

2021-03-24 09:08 UTC, ligi approved these changes

2021-03-25 17:21 UTC, shrugs commented
@ligi are there any extra pending approvals?

2021-03-25 19:04 UTC, merged

2021-03-25 19:04 UTC, ligi commented
I hoped @pedrouid would also approve - but I think 3 is good enough