Add CAIP-2 for Solana
ChainAgnostic/CAIPs pull request #60
Opened 2021-08-04 17:57 UTC by antoineherzog

2021-08-06 13:53 UTC, antoineherzog commented
Hello! Any feedbacks regarding CAIP-2 for Solana 👀

2021-08-10 11:13 UTC, antoineherzog commented
@pedrouid @ligi  ? :)

2021-08-10 12:44 UTC, ligi requested changes

2021-08-10 12:44 UTC, ligi commented on CAIPs/caip-30.md
> +discussions-to: []
```suggestion
discussions-to: https://github.com/ChainAgnostic/CAIPs/pull/60
```

2021-08-10 12:44 UTC, ligi commented on CAIPs/caip-30.md
> +This document is about the details of the Solana namespaces and references for CAIP-2.
```suggestion
This document is about the details of the Solana namespace and reference for CAIP-2.
```

2021-08-10 12:47 UTC, ligi commented
sorry was on the road for a bit - just some minor change suggestions. 
And I found it a bit weird that there is a getGenesisHash function. Sounds a bit weird to have a specail function for this and not use the standard get block by number for block 0.

2021-08-10 13:13 UTC, antoineherzog commented
No prob! I've just addressed for your feedbacks.
Solana also have the get block by number function however Joshua told me that we could use the `getGenesisHash`function.

2021-08-12 17:14 UTC, antoineherzog commented
@pedrouid any feedback?

2021-08-13 09:44 UTC, pedrouid commented
LGTM 👍 Thanks for submitting it @antoineherzog. I was also going to need this 😅

2021-08-16 08:13 UTC, antoineherzog commented
@ligi lets merge?

2021-08-16 08:14 UTC, ligi approved these changes

2021-08-16 08:14 UTC, merged

2021-08-16 08:28 UTC, ligi commented
@pedrouid better leave a approval than a LGTM comment - makes it easier to see if there are 2 approvals than reading the comments.

2021-08-16 08:37 UTC, pedrouid commented
> @pedrouid better leave a approval than a LGTM comment - makes it easier to see if there are 2 approvals than reading the comments.

My bad. You’re right