Draft: Add GPG namespace
ChainAgnostic/CAIPs pull request #66
Opened 2021-09-02 10:39 UTC by sebastinez

This PR proposes the implementation of the GPG namespace.

Discussion is located in #65

2022-01-13 16:10 UTC, ligi requested changes

2022-01-13 16:10 UTC, ligi commented on CAIPs/caip-draft-gpg.md
> +requires: X
```suggestion
requires: 2
```

2022-02-10 16:22 UTC, bumblefudge commented
Discussed at last meeting, leaving open pending as-yet undefined Namespaces policy on non-chain crypto systems. At this meeting, we also noted we should document better where new namespace definiions will go (/namespaces/).  We also discussed the distinction between caip:gpg and caip:gpg-vks (https://keys.openpgp.org/about/api)-- how VKS could fit was discussed.

2022-02-10 16:22 UTC, bumblefudge commented
Removed next meeting tag and will return to this issue after editorial namespace overhaul and discussions of non-chain boundary of this group's scope

2022-11-04 16:14 UTC, silverpill commented
What's the status of this?
Are non-blockchain namespaces allowed?

2023-04-28 22:51 UTC, obstropolos commented
Doing some cleanup here - we've now moved all namespace requests to the namespaces repo. If this discussion is to continue, please reopen this in the namespaces repo: https://github.com/chainagnostic/namespaces - thanks!

2023-04-28 22:51 UTC, closed without merging